import { FC } from "react";
import type { IChildren } from "../interfaces/index";
import Head from "next/head";
import Navbar from "../components/Navbar";

const LayoutPrincipal: FC<IChildren> = ({ children }): JSX.Element => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./assets/favicon-32x32.png"
        />
      </Head>
      <Navbar />
      <main>
        {children}
      </main>
    </>
  );
};

export default LayoutPrincipal;
